spring:
  application:
    name: labo-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  management:
    endpoints:
      web:
        exposure:
          include: "*"

